name: sad

base: core18

version: "0.4.4"

summary: |-
  Search and replace | Space Age seD

description: |-
  sad is a regex search / replace tool. it provides vastly
  improved ergonomics over sed.

  * amazing terminal UI.
  * preview changes
  * selectively apply changes
  * batch mode

  integrates with fzf, diff-so-fancy, delta

  https://github.com/ms-jpq/sad


grade: stable
confinement: devmode

apps:
  sad:
    command: sad

parts:
  sad:
    plugin: rust
    source: https://github.com/ms-jpq/sad.git
